name: Update Pac-Man

on:
  schedule:
    - cron: "0 0 * * *"  # update tiap hari
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Generate Pacman SVG
        run: python scripts/generate_pacman.py

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add assets/pacman.svg
          git commit -m "update pacman status" || echo "No changes to commit"
          git push
